# Usa una imagen base de Nginx
FROM nginx:alpine

# Copia tu archivo HTML al directorio de documentos raíz de Nginx
COPY . /usr/share/nginx/html

# Nginx ya inicia automáticamente al contenedor, por lo que no necesitas una instrucción CMD.